/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cbi.frames;

import br.com.cbi.listeners.Listener_Entidades;
import br.com.fs.api.annotations.MapFrameField;
import br.com.fs.api.beans.JTextFieldCBI;
import br.com.fs.api.beans.MenuBarCbiDefault;
import br.com.fs.api.interfaces.ManipulaFrames;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Tiago
 */
public final class Form_Entidades extends ManipulaFrames {

    private static final long serialVersionUID = 2760168823831208647L;
    private final MenuBarCbiDefault menuBarCbiDefault = new MenuBarCbiDefault();
    private final Listener_Entidades listener;

    /**
     * Creates new form Form_Entidades
     */
    public Form_Entidades() {
        setImageIcon();
        this.setJMenuBar(menuBarCbiDefault);
        initComponents();
        listener = new Listener_Entidades(this);
    }

    @Override
    public Optional<List<JPanel>> getListPaineis() {
        return Optional.of(Arrays.asList(painelSuperior, painelChecks, painelEmails, painelEnderecos, painelTelefones));
    }

    @MapFrameField(referencedField = "tipo_entidade_string", typeParameter = String.class)
    public JComboBox<String> getCbTipoEntidade() {
        return cbTipoEntidade;
    }

    @MapFrameField(referencedField = "cliente", typeParameter = Boolean.class)
    public JCheckBox getCkCliente() {
        return ckCliente;
    }

    @MapFrameField(referencedField = "empresa", typeParameter = Boolean.class)
    public JCheckBox getCkEmpresa() {
        return ckEmpresa;
    }

    @MapFrameField(referencedField = "fornecedor", typeParameter = Boolean.class)
    public JCheckBox getCkFornecedor() {
        return ckFornecedor;
    }

    @MapFrameField(referencedField = "emails", typeParameter = List.class)
    public JTable getTbEmails() {
        return tbEmails;
    }

    @MapFrameField(referencedField = "enderecos", typeParameter = List.class)
    public JTable getTbEnderecos() {
        return tbEnderecos;
    }

    @MapFrameField(referencedField = "telefones", typeParameter = List.class)
    public JTable getTbTelefones() {
        return tbTelefones;
    }

    @MapFrameField(referencedField = "data_cadastro", typeParameter = LocalDateTime.class)
    public JTextFieldCBI getTxtData() {
        return txtData;
    }

    @MapFrameField(referencedField = "id", typeParameter = Long.class)
    public JTextField getTxtId() {
        return txtId;
    }

    @MapFrameField(referencedField = "nome_fantasia", typeParameter = String.class)
    public JTextFieldCBI getTxtNomeFantasia() {
        return txtNomeFantasia;
    }

    @MapFrameField(referencedField = "razao_social", typeParameter = String.class)
    public JTextFieldCBI getTxtRazaoSocial() {
        return txtRazaoSocial;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtData = new br.com.fs.api.beans.JTextFieldCBI();
        cbTipoEntidade = new javax.swing.JComboBox<>();
        painelChecks = new javax.swing.JPanel();
        ckCliente = new javax.swing.JCheckBox();
        ckFornecedor = new javax.swing.JCheckBox();
        ckEmpresa = new javax.swing.JCheckBox();
        txtRazaoSocial = new br.com.fs.api.beans.JTextFieldCBI();
        txtNomeFantasia = new br.com.fs.api.beans.JTextFieldCBI();
        painelGuias = new javax.swing.JTabbedPane();
        painelEnderecos = new javax.swing.JPanel();
        scEnderecos = new javax.swing.JScrollPane();
        tbEnderecos = new javax.swing.JTable();
        painelTelefones = new javax.swing.JPanel();
        scTelefones = new javax.swing.JScrollPane();
        tbTelefones = new javax.swing.JTable();
        painelEmails = new javax.swing.JPanel();
        scEmails = new javax.swing.JScrollPane();
        tbEmails = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Entidades");

        jLabel1.setText("Id");

        jLabel2.setText("Data de Cadastro");

        jLabel3.setText("Tipo de Entidade");

        jLabel4.setText("Razão Social");

        jLabel5.setText("Nome Fantasia");

        txtId.setEditable(false);
        txtId.setEnabled(false);

        txtData.setEnabled(false);
        txtData.setMaxLength(10);
        txtData.setName("data"); // NOI18N

        cbTipoEntidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jurídica", "Física" }));
        cbTipoEntidade.setEnabled(false);

        ckCliente.setText("Cliente");
        ckCliente.setEnabled(false);

        ckFornecedor.setText("Fornecedor");
        ckFornecedor.setEnabled(false);

        ckEmpresa.setText("Empresa");
        ckEmpresa.setEnabled(false);

        javax.swing.GroupLayout painelChecksLayout = new javax.swing.GroupLayout(painelChecks);
        painelChecks.setLayout(painelChecksLayout);
        painelChecksLayout.setHorizontalGroup(
            painelChecksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelChecksLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(ckCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ckEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelChecksLayout.setVerticalGroup(
            painelChecksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelChecksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelChecksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckCliente)
                    .addComponent(ckFornecedor)
                    .addComponent(ckEmpresa))
                .addGap(0, 0, 0))
        );

        txtRazaoSocial.setEnabled(false);
        txtRazaoSocial.setMaxLength(255);
        txtRazaoSocial.setName("data"); // NOI18N

        txtNomeFantasia.setEnabled(false);
        txtNomeFantasia.setMaxLength(255);
        txtNomeFantasia.setName("data"); // NOI18N

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelSuperiorLayout.createSequentialGroup()
                        .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTipoEntidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelChecks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNomeFantasia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelChecks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelSuperiorLayout.createSequentialGroup()
                        .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTipoEntidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbEnderecos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEnderecos.setEnabled(false);
        scEnderecos.setViewportView(tbEnderecos);

        javax.swing.GroupLayout painelEnderecosLayout = new javax.swing.GroupLayout(painelEnderecos);
        painelEnderecos.setLayout(painelEnderecosLayout);
        painelEnderecosLayout.setHorizontalGroup(
            painelEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scEnderecos, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelEnderecosLayout.setVerticalGroup(
            painelEnderecosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEnderecosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scEnderecos, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelGuias.addTab("Endereços", painelEnderecos);

        tbTelefones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTelefones.setEnabled(false);
        scTelefones.setViewportView(tbTelefones);

        javax.swing.GroupLayout painelTelefonesLayout = new javax.swing.GroupLayout(painelTelefones);
        painelTelefones.setLayout(painelTelefonesLayout);
        painelTelefonesLayout.setHorizontalGroup(
            painelTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelefonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scTelefones, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelTelefonesLayout.setVerticalGroup(
            painelTelefonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelefonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scTelefones, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelGuias.addTab("Telefones", painelTelefones);

        scEmails.setDoubleBuffered(true);
        scEmails.setEnabled(false);

        tbEmails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scEmails.setViewportView(tbEmails);

        javax.swing.GroupLayout painelEmailsLayout = new javax.swing.GroupLayout(painelEmails);
        painelEmails.setLayout(painelEmailsLayout);
        painelEmailsLayout.setHorizontalGroup(
            painelEmailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEmailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scEmails, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelEmailsLayout.setVerticalGroup(
            painelEmailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEmailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scEmails, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelGuias.addTab("E-mails", painelEmails);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelGuias)
            .addComponent(painelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelGuias)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Entidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Entidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Entidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Entidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Entidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbTipoEntidade;
    private javax.swing.JCheckBox ckCliente;
    private javax.swing.JCheckBox ckEmpresa;
    private javax.swing.JCheckBox ckFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel painelChecks;
    private javax.swing.JPanel painelEmails;
    private javax.swing.JPanel painelEnderecos;
    private javax.swing.JTabbedPane painelGuias;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JPanel painelTelefones;
    private javax.swing.JScrollPane scEmails;
    private javax.swing.JScrollPane scEnderecos;
    private javax.swing.JScrollPane scTelefones;
    private javax.swing.JTable tbEmails;
    private javax.swing.JTable tbEnderecos;
    private javax.swing.JTable tbTelefones;
    private br.com.fs.api.beans.JTextFieldCBI txtData;
    private javax.swing.JTextField txtId;
    private br.com.fs.api.beans.JTextFieldCBI txtNomeFantasia;
    private br.com.fs.api.beans.JTextFieldCBI txtRazaoSocial;
    // End of variables declaration//GEN-END:variables
}
